version: "3"

services:

    web_secret:
        build: ./web
        restart: always
        environment:
            - APACHE_RUN_USER=#1000
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
            - 10070:80
        working_dir: ${APP_PATH_CONTAINER}

    db_secret:
        build: ./db
        command: "--innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: secret.api_db
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql

    phpmyadmin_secret:
        build: ./phpmyadmin
        links:
            - db_secret
        restart: always
        ports:
            - 10071:80
        environment:
            - PMA_HOST=db_secret
            - PMA_PORT=3306
            - PMA_ARBITRARY=1

    composer_secret:
        image: composer
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install
